### ISSUE TITLE
Widgets Link missing '/' at the beggining

### ISSUE THREAD

**Issue by fruscitti** [bradwestfall/CSS-Tricks-React-Series#15]
Its a little detail, but:

The line:
            <li><Link to="widgets" activeClassName="active">Widgets</Link></li>
should be:
            <li><Link to="**/**widgets" activeClassName="active">Widgets</Link></li>

Because if not, if you navigate to users, click on an user, and then click on Widgets, you get an incorrect URL of the form:
/users/widgets.

Then if you hit Refresh (F5) you get an incorrect component.

**Comment by bradwestfall** [comment]
Got it
