### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by kbariotis** [bradwestfall/CSS-Tricks-React-Series#16]
Is [this](https://github.com/bradwestfall/CSS-Tricks-React-Series/blob/master/guide-3-redux/app/components/views/search-form.js) intentionally not became a Stateless Functional Component?

Thank you

**Comment by bradwestfall** [comment]
Since there's two methods, `render` and `getQuery`, it can't be. Unless there's something I'm missing

**Comment by kbariotis** [comment]
[Here's](https://medium.com/@housecor/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc#.1notdbra6) an example of having more than one method in an SFC. So this can't be the reason.

**Comment by bradwestfall** [comment]
Oh yea, so I guess you can do that. I won't be writing SFC that way but you can if you want
