### ISSUE TITLE
Don't Call PropTypes Warning

### ISSUE THREAD

**Issue by psunderr** [bradwestfall/CSS-Tricks-React-Series#17]
![image](https://cloud.githubusercontent.com/assets/13961017/21998796/ba339220-dbeb-11e6-8781-7d9dd6ea57ed.png)

Is there a simple solution to these PropTypes warnings to ensure that the code doesn't crash in future React versions?

**Comment by bradwestfall** [comment]
I'm not really familiar with the issue, so what's going on?

**Comment by psunderr** [comment]
I'm not entirely sure, I thought you might be familiar with it. It won't break the code until React 16, and apparently only in production builds. Documentation for the warning can be found here but I'll have to look into it when I have a little more time to spare: [https://facebook.github.io/react/warnings/dont-call-proptypes.html](https://facebook.github.io/react/warnings/dont-call-proptypes.html).

**Comment by bradwestfall** [comment]
hmm, ok. Well after reading that, I can say I'm not calling propTypes directly. Plus the code for the repo is built as dev code not production code. So if that screenshot is coming from this code, I don't know what's causing it. Maybe one of the third-party libs.
