### ISSUE TITLE
"global" store

### ISSUE THREAD

**Issue by allevo** [bradwestfall/CSS-Tricks-React-Series#18]
I'm concerned about the store variable export

https://github.com/bradwestfall/CSS-Tricks-React-Series/blob/master/guide-3-redux/app/store.js#L5

It is used, for example, here:

https://github.com/bradwestfall/CSS-Tricks-React-Series/blob/master/guide-3-redux/app/api/user-api.js#L36

where the `dispatch` function is not available.

Broadly speaking, this happens when, after a `write` operation, you want to refresh the application state, for example refreshing the user list.

Is this a good practice for large application?

**Comment by bradwestfall** [comment]
I'm not quite sure what you mean. The `store` variable isn't global, it's imported on that second example you were showing

**Comment by allevo** [comment]
Yes, the `store` variable is not a typical global variable. (like `window.store`)

But is accessible from whole modules of the code. It is not protected and reducers, components, containers, actions and apis can access and modify it directly.

**Comment by bradwestfall** [comment]
I don't know that I see a problem with the strategy. Sometimes you need access to the store, so I export it

**Comment by welly** [comment]
What @bradwestfall has done seems to be a standard pattern. If you're concerned about mutability of the store, you can install immutable.js or redux-immutable-state-invariant to catch any direct state changes.

**Comment by bradwestfall** [comment]
I forgot to close this a while back, closing now
