### ISSUE TITLE
users not reachable to twitter issue in guide-2

### ISSUE THREAD

**Issue by sauhungyu** [bradwestfall/CSS-Tricks-React-Series#19]
Brad,

Appreciated your fix promptly in user-profile.js for typo error. However, i downloaded the fix again to find the problem still there.  It looked as if the change was ignored by Webpack.  After trying with installing gulp globally and running npm start and gulp watch in two terminals.  The browser slowly reflected what it should be.  However,  i really not sure whether it needs these to Webpack to effect the change. I only know that doing gulp watch can rebuild the bundle.js from webpack for change made to any file as the bundle.js is necessary for browser to refresh after changes.  Please suggest what i did is right or not.  Thanks.

**Comment by bradwestfall** [comment]
Hi @sauhungyu I think it's because I needed to re-build the code. This project has it's "built-code" as apart of the repo to make it easier for people to clone and run. So you can either pull the new code down or do `gulp build` in the respective guide folder.
