### ISSUE TITLE
Mention .babelrc

### ISSUE THREAD

**Issue by rivella50** [bradwestfall/CSS-Tricks-React-Series#2]
Hi,
first of all thank you very much for this series of 3 tutorials. Great work and effort from your side.
I just started a brand new project based on your 2nd tutorial and needed some time to figure out
why i got an error message like this on startup:

```
import express from 'express';
^^^^^^
SyntaxError: Unexpected reserved word
```

A stackoverflow tip mentioned to create the file .babelrc in the root directory.
I would add a sentence on your main page too which mentions this aspect in order that Babel starts working.

**Comment by bradwestfall** [comment]
That's strange, the repo has `.babelrc` files for each of the three guides. Did they not come over on the clone?

**Comment by rivella50** [comment]
Yes of course, your guides include these files, also when they are cloned.
But i thought i could be worth mentioning in your documentation what they are good for.
As i said i started a brand new project (i.e. not cloning one of your guides) and then i had
to learn first that a `.babelrc` file is needed.

**Comment by bradwestfall** [comment]
I can add that do the docs

**Comment by rivella50** [comment]
Cool, thank you very much!
