### ISSUE TITLE
cannot use dispatch() on IE11

### ISSUE THREAD

**Issue by distravantari** [bradwestfall/CSS-Tricks-React-Series#7]
I try to run it on chrome and other browser and it works completely fine, but when I use IE the users and widgets on the list is zero, or no list of user/widget at all.

is there any other way to dispatch store using IE ?

**Comment by bradwestfall** [comment]
It's probably not an issue with dispatch but something else I'm doing. Im on a mac so it would be some work for me to setup IE testing, but what version of IE is not working, maybe I can get to it at some point

**Comment by tswaters** [comment]
First error I get in IE is `Promise is not defined` 

It seems axios uses Promises:  https://github.com/mzabriskie/axios#promises

IE doesn't support global `Promise` object and will need a polyfill for this to work properly.

**Comment by bradwestfall** [comment]
Thanks @tswaters, I implemented the polyfill. I cannot test though, so if you want to test for IE that would be great

**Comment by tswaters** [comment]
With the promise polyfill in place, it is now failing on `Object.assign`.... there's a babel plugin for that, see PR.  This only affects guide-3
