### ISSUE TITLE
api(json-server) not starting in windows if path has spaces

### ISSUE THREAD

**Issue by matthiasprieth** [bradwestfall/CSS-Tricks-React-Series#8]
The json-server is not starting for windows if there are spaces in the path.

> c:\program' is not recognized as a command

Errors are coming from the gulpfile.js. It's working for me at the moment if I'm adding quotes to the `__dirname`, but I guess that's not the right solution.
`gulpfile.js:43&54` `var serverPath = path.join('"'+__dirname+'"', 'node_modules/.bin/json-server');`

Big thumps up for the tutorial/article! :+1:

**Comment by bradwestfall** [comment]
Thanks @matthiasprieth 

I don't know a whole lot about running Node on Windows. Yea that quotes solution seems odd that it would work. If you end up figuring out a solution that works on Windows and doesn't break for non-Windows users, we can do a PR

**Comment by tswaters** [comment]
I would think the same issue would show up in any os when the repo is cloned into a directory with spaces... while less common in unix/mac it's totally possible to have spaces in directories.

As I see it, it can be resolved in the following ways:
- don't reference `__dirname`, use a relative path, ensure it includes node and goes to the js file, 
  e.g. `cp.exec("node ./node_modules/json-server/bin/index.js ...etc...")`
- escape spaces with a `\` (see http://stackoverflow.com/a/26998326)
- wrap serverPath in quotes.  (I would think a cleaner way is the following:

``` js
cp.exec(`"${serverPath}" ...etc...`)
```

I'm pretty sure each will work in both posix/non-posix systems.

**Comment by bradwestfall** [comment]
Ok, it was relative path at first and then this came up in #1 for Windows, so we switched to the recent strategy. I can't test on Windows so I'm relying on you. Switched back to relative path, please test.

**Comment by tswaters** [comment]
Not quite, it needs the node executable there and it needs to reference the actual js file inside the node_module.  

The ones under .bin include os-specific shell scripts which can't be called directly in a platform-agnostic way.  Each one does call `node` and a file, so it can be done directly like that.  I've added a PR that fixes this.

**Comment by bradwestfall** [comment]
Welp, if you'd like to do all the Windows users a favor, you can do a PR. I'm not going to play the guessing game. I don't have windows

**Comment by bradwestfall** [comment]
nm, I see your PR, I'll take a look later today
