### ISSUE TITLE
Question About Passing Props to Stateless Components

### ISSUE THREAD

**Issue by lsbyerley** [bradwestfall/CSS-Tricks-React-Series#9]
I recently came across this series on css-tricks and I have to say it's one of the best React tutorials I've found. This isn't really an issue as it is more of a question. I'm currently working on converting my website over to React using this tutorial. I have a layout component with Nav, Header, Footer components all of which are stateless functional components. Some of my pages do not use the header, and the ones that do need to have a class on them designating a background image to use. My question is, without making a separate layout without the header component, what is the best way to pass props from the router to the header component to either add a class, or not show it at all? Or is passing props from the router not a viable approach?

**Comment by bradwestfall** [comment]
Thanks @lsbyerley 

Not sure passing your own props from React Router down to the layout will workout. Sounds like you might need to slightly different layouts, one with header and one without. Or you can just have one layout and determine if the header should be placed depending on state (redux) if that works out better
